[package]
name = "canal-test"
version = "0.1.0"
edition = "2021"

[dependencies]
canal-common = { path = "../canal-common" }
network-types = "0.0.7"
nix = { version = "0.29.0", features = ["socket", "user"] }
tokio = { version = "1.4", features = ["full"] }